kubectl apply -f /var/lib/jenkins/workspace/Dev-Ops-Proj/kubernets/db-secret.yaml
kubectl apply -f /var/lib/jenkins/workspace/Dev-Ops-Proj/kubernets/nginx-deploy.yaml
kubectl apply -f /var/lib/jenkins/workspace/Dev-Ops-Proj/kubernets/nginx-serv.yaml
kubectl apply -f /var/lib/jenkins/workspace/Dev-Ops-Proj/kubernets/nginx-conf.yaml
kubectl apply -f /var/lib/jenkins/workspace/Dev-Ops-Proj/kubernets/frontend-serv.yaml
kubectl apply -f /var/lib/jenkins/workspace/Dev-Ops-Proj/kubernets/frontend-deploy.yaml
kubectl apply -f /var/lib/jenkins/workspace/Dev-Ops-Proj/kubernets/backend-serv.yaml
kubectl apply -f /var/lib/jenkins/workspace/Dev-Ops-Proj/kubernets/backend-deploy.yaml
kubectl apply -f /var/lib/jenkins/workspace/Dev-Ops-Proj/kubernets/db.yaml