apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: proj
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dylanrit/backend:latest
        imagePullPolicy: "Always"
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: db-uri
              key: DATABASE_URI
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-key
              key: SECRET_KEY
              ports:
                - containerPort: 5001