apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: proj
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

