version: "3.8"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    depends_on:
      - "backend"
  backend:
    container_name: backend
    build: ./backend
    image: backend
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    depends_on:
      - "database"
  database:
    container_name: database
    build: ./database
    image: database
    ports:
      - target: 3306
        published: 3306
        protocol: tcp