version: "3.8"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend
    ports:
      - target: 5000
        published: 5000
        protocol: tcp

  backend:
    container_name: backend
    build: ./backend
    image: backend
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
#    environment:
#      DATABASE_URI: ${DATABASE_URI}
#      TEST_DATABASE_URI: ${TEST_DATABASE_URI}
#      SECRET_KEY: ${DATABASE_SECRET_KEY}

